name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Build, tag, and push the image
      - name: Build and push Docker image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/logistik
          IMAGE_ID=$(echo "$IMAGE_ID" | tr '[:upper:]' '[:lower:]')

          echo "Building image: ${IMAGE_ID}:${{ github.sha }}"
          docker build -t ${IMAGE_ID}:${{ github.sha }} .

          echo "Pushing image with SHA tag..."
          docker push ${IMAGE_ID}:${{ github.sha }}

          echo "Tagging as latest..."
          docker tag ${IMAGE_ID}:${{ github.sha }} ${IMAGE_ID}:latest
          docker push ${IMAGE_ID}:latest
